import type { MapAsset, TrackCorner, TrackLayout, TrackMapData } from "./types";

/**
 * Circuit maps that ship with the app.
 *
 * Each layout carries its own version stamp. The artwork is copied into IndexedDB the first time
 * a track uses it, so without a stamp a corrected map never reaches a device that already stored
 * the old one — and a single shared stamp would push every built-in map again whenever one of
 * them changed.
 */
export type BuiltInLayout = {
  /** Stable identity written onto the stored layout, so a renamed layout is still recognised. */
  key: string;
  name: string;
  mapUrl: string;
  version: string;
  corners: TrackCorner[];
};

export type BuiltInTrack = {
  key: string;
  name: string;
  location: string;
  notes: string;
  /** Every built-in circuit here runs clockwise; taken from the loop orientation, not assumed. */
  direction: TrackLayout["direction"];
  attribution: string;
  sourceUrl: string;
  layouts: BuiltInLayout[];
};

const OSM_ATTRIBUTION = "Geometry derived from OpenStreetMap contributors · ODbL 1.0";
const OSM_SOURCE_URL = "https://www.openstreetmap.org/copyright";

// Derived by scripts/derive-corners.mjs from the shipped SVG's own path geometry. Re-run that
// script if the artwork changes; do not hand-edit. Lap order starts at the Sector 1 line.
export const BUILT_IN_PFI_CORNERS: TrackCorner[] = [
  { number: 1, label: "T1", x: 0.4214, y: 0.5753 },
  { number: 2, label: "T2", x: 0.2903, y: 0.5957 },
  { number: 3, label: "T3", x: 0.2011, y: 0.6778 },
  { number: 4, label: "T4", x: 0.0808, y: 0.7548 },
  { number: 5, label: "T5", x: 0.3283, y: 0.6857 },
  { number: 6, label: "T6", x: 0.1478, y: 0.6519 },
  { number: 7, label: "T7", x: 0.4859, y: 0.3213 },
  { number: 8, label: "T8", x: 0.3403, y: 0.5312 },
  { number: 9, label: "T9", x: 0.5839, y: 0.3177 },
  { number: 10, label: "T10", x: 0.4791, y: 0.2749 },
  { number: 11, label: "T11", x: 0.645, y: 0.0836 },
  { number: 12, label: "T12", x: 0.8326, y: 0.147 },
  { number: 13, label: "T13", x: 0.6883, y: 0.1238 },
  { number: 14, label: "T14", x: 0.6034, y: 0.2136 },
  { number: 15, label: "T15", x: 0.7161, y: 0.2653 },
];

// Generated by scripts/build-whilton-maps.mjs alongside the artwork it labels. Re-run that
// script if the map changes; do not hand-edit.
export const BUILT_IN_WHILTON_INTERNATIONAL_CORNERS: TrackCorner[] = [
  { number: 1, label: "T1", x: 0.1383, y: 0.3182 },
  { number: 2, label: "T2", x: 0.8548, y: 0.148 },
  { number: 3, label: "T3", x: 0.7855, y: 0.2644 },
  { number: 4, label: "T4", x: 0.8533, y: 0.4279 },
  { number: 5, label: "T5", x: 0.5625, y: 0.5833 },
  { number: 6, label: "T6", x: 0.6608, y: 0.256 },
  { number: 7, label: "T7", x: 0.3283, y: 0.2752 },
  { number: 8, label: "T8", x: 0.4601, y: 0.7212 },
  { number: 9, label: "T9", x: 0.6087, y: 0.7392 },
  { number: 10, label: "T10", x: 0.5754, y: 0.8249 },
  { number: 11, label: "T11", x: 0.318, y: 0.8251 },
];




const WHILTON_VERSION = "2026-08-19-osm-derived";

export const BUILT_IN_TRACKS: BuiltInTrack[] = [
  {
    key: "pf-international",
    name: "PF International",
    location: "Grantham, UK",
    notes: "",
    direction: "Clockwise",
    attribution: OSM_ATTRIBUTION,
    sourceUrl: OSM_SOURCE_URL,
    layouts: [{
      key: "pfi-full",
      name: "Full Layout",
      mapUrl: "/maps/pfi-international-owner-driver.svg",
      version: "2026-08-16-numbered-corners",
      corners: BUILT_IN_PFI_CORNERS,
    }],
  },
  {
    key: "whilton-mill",
    name: "Whilton Mill",
    location: "Daventry, UK",
    // The lap length is the measured centreline of the OpenStreetMap geometry, which runs shorter
    // than the figures the circuit publishes. Recorded here so the number on the map is not
    // mistaken for an official distance.
    notes: "The lap length shown on the map is measured along the OpenStreetMap centreline, not the circuit's published distance.",
    direction: "Clockwise",
    attribution: OSM_ATTRIBUTION,
    sourceUrl: OSM_SOURCE_URL,
    layouts: [{
      key: "whilton-international",
      name: "International",
      mapUrl: "/maps/whilton-mill-international.svg",
      version: WHILTON_VERSION,
      corners: BUILT_IN_WHILTON_INTERNATIONAL_CORNERS,
    }],
  },
];

const layoutsByKey = new Map(BUILT_IN_TRACKS.flatMap((track) => track.layouts.map((layout) => [layout.key, { track, layout }] as const)));

/**
 * Loads a map that ships with the app. Width and height come from the file's own viewBox rather
 * than being hard-coded at the call site: marker positions are stored as fractions of the asset
 * box, so a stored size that disagrees with the artwork letterboxes the image and drifts every
 * marker placed on it.
 */
export async function loadBuiltInMapAsset(url: string): Promise<MapAsset> {
  const response = await fetch(url);
  if (!response.ok) throw new Error("Built-in map unavailable.");
  const markup = await response.text();

  const viewBox = markup.match(/viewBox\s*=\s*"\s*[\d.-]+\s+[\d.-]+\s+([\d.]+)\s+([\d.]+)/);
  const width = Number(viewBox?.[1]);
  const height = Number(viewBox?.[2]);
  if (!Number.isFinite(width) || !Number.isFinite(height) || width <= 0 || height <= 0) {
    throw new Error("Built-in map has no usable viewBox.");
  }

  const blob = new Blob([markup], { type: "image/svg+xml" });
  return {
    id: crypto.randomUUID(),
    blob,
    width,
    height,
    mimeType: "image/svg+xml",
    size: blob.size,
    updatedAt: new Date().toISOString(),
  };
}

/** The fields a stored layout needs in order to carry, and later recognise, a built-in map. */
export function builtInLayoutFields(track: BuiltInTrack, layout: BuiltInLayout, asset: MapAsset) {
  return {
    mapAssetId: asset.id,
    sourceAttribution: track.attribution,
    sourceUrl: track.sourceUrl,
    builtInLayoutKey: layout.key,
    builtInMapVersion: layout.version,
    corners: layout.corners,
  };
}

/**
 * Identifies the built-in layout a stored record came from.
 *
 * The key is authoritative. Records created before keys existed have none, so PF International is
 * also matched on the track and layout names it was created with — the only built-in track that
 * could have been stored back then. That fallback is deliberately not extended to Whilton Mill:
 * no unkeyed Whilton Mill record can exist, so name-matching one could only ever capture a track
 * the user built themselves and overwrite their map.
 */
function builtInLayoutFor(data: TrackMapData, layout: TrackLayout) {
  if (layout.builtInLayoutKey) return layoutsByKey.get(layout.builtInLayoutKey);

  const track = data.tracks.find((candidate) => candidate.id === layout.trackId);
  const isLegacyPfi = track?.name.trim().toLowerCase() === "pf international" && layout.name.trim().toLowerCase() === "full layout";
  return isLegacyPfi ? layoutsByKey.get("pfi-full") : undefined;
}

/**
 * Attaches built-in maps to layouts that need one, and replaces the artwork on layouts still
 * holding an older version of it.
 *
 * A layout whose map the user replaced has no `sourceAttribution` (uploadImage clears it), which
 * is what marks it as user-owned and off-limits here. Returns the input unchanged when there is
 * nothing to do, so callers can assign the result unconditionally.
 */
export async function refreshBuiltInMaps(data: TrackMapData): Promise<TrackMapData> {
  const stale = data.layouts
    .map((layout) => ({ layout, builtIn: builtInLayoutFor(data, layout) }))
    .filter((entry): entry is { layout: TrackLayout; builtIn: NonNullable<ReturnType<typeof builtInLayoutFor>> } => {
      if (!entry.builtIn) return false;
      const carriesBuiltInMap = !entry.layout.mapAssetId || Boolean(entry.layout.sourceAttribution);
      return carriesBuiltInMap && entry.layout.builtInMapVersion !== entry.builtIn.layout.version;
    });
  if (!stale.length) return data;

  // One fetch per distinct map, however many layouts are waiting on it.
  const urls = [...new Set(stale.map((entry) => entry.builtIn.layout.mapUrl))];
  const assets = new Map(await Promise.all(urls.map(async (url) => [url, await loadBuiltInMapAsset(url)] as const)));

  const fieldsByLayoutId = new Map(stale.map((entry) => [
    entry.layout.id,
    builtInLayoutFields(entry.builtIn.track, entry.builtIn.layout, assets.get(entry.builtIn.layout.mapUrl)!),
  ]));
  const replacedAssetIds = new Set(stale.map((entry) => entry.layout.mapAssetId).filter((id): id is string => Boolean(id)));
  const timestamp = new Date().toISOString();

  return {
    ...data,
    assets: [...data.assets.filter((candidate) => !replacedAssetIds.has(candidate.id)), ...assets.values()],
    layouts: data.layouts.map((layout) => {
      const fields = fieldsByLayoutId.get(layout.id);
      return fields ? { ...layout, ...fields, updatedAt: timestamp } : layout;
    }),
  };
}

/**
 * Builds the Track and Layout records for a built-in circuit, ready to append to the store.
 *
 * A map that fails to load is not fatal: the track is still created without one, and
 * refreshBuiltInMaps attaches the artwork on a later load once the file is reachable.
 */
export async function createBuiltInTrack(track: BuiltInTrack, timestamp: string) {
  const trackId = crypto.randomUUID();
  const assets: MapAsset[] = [];

  const layouts = await Promise.all(track.layouts.map(async (layout) => {
    let asset: MapAsset | undefined;
    try {
      asset = await loadBuiltInMapAsset(layout.mapUrl);
      assets.push(asset);
    } catch {
      // Leave the layout without a map; the user can upload one or reload to pick it up.
    }
    return {
      id: crypto.randomUUID(),
      trackId,
      name: layout.name,
      direction: track.direction,
      // The key and corners are stored either way, so a layout whose artwork failed to load is
      // still recognised as built-in and picks the map up on a later load.
      ...(asset
        ? builtInLayoutFields(track, layout, asset)
        : { mapAssetId: null, builtInLayoutKey: layout.key, corners: layout.corners }),
      markers: [],
      createdAt: timestamp,
      updatedAt: timestamp,
    } satisfies TrackLayout;
  }));

  return {
    track: { id: trackId, name: track.name, location: track.location, notes: track.notes, createdAt: timestamp, updatedAt: timestamp },
    layouts,
    assets,
    mapsLoaded: assets.length,
  };
}
