import type { MapAsset, TrackCorner, TrackLayout, TrackMapData } from "./types";

/**
 * Circuit maps that ship with the app.
 *
 * Each layout carries its own version stamp. The artwork is copied into IndexedDB the first time
 * a track uses it, so without a stamp a corrected map never reaches a device that already stored
 * the old one — and a single shared stamp would push every built-in map again whenever one of
 * them changed.
 */
export type BuiltInLayout = {
  /** Stable identity written onto the stored layout, so a renamed layout is still recognised. */
  key: string;
  name: string;
  mapUrl: string;
  version: string;
  corners: TrackCorner[];
};

export type BuiltInTrack = {
  key: string;
  name: string;
  location: string;
  notes: string;
  /**
   * Taken from the loop orientation where the source records one. Kart Silverstone has no oneway
   * tagging in OpenStreetMap, so its anti-clockwise direction comes from the owner instead — but
   * it is never guessed: a direction nobody has confirmed stays Unknown.
   */
  direction: TrackLayout["direction"];
  attribution: string;
  sourceUrl: string;
  layouts: BuiltInLayout[];
};

const OSM_ATTRIBUTION = "Geometry derived from OpenStreetMap contributors · ODbL 1.0";
const OSM_SOURCE_URL = "https://www.openstreetmap.org/copyright";

// Derived by scripts/derive-corners.mjs from the shipped SVG's own path geometry. Re-run that
// script if the artwork changes; do not hand-edit. Lap order starts at the Sector 1 line.
export const BUILT_IN_PFI_CORNERS: TrackCorner[] = [
  { number: 1, label: "T1", x: 0.4214, y: 0.5753 },
  { number: 2, label: "T2", x: 0.2903, y: 0.5957 },
  { number: 3, label: "T3", x: 0.2011, y: 0.6778 },
  { number: 4, label: "T4", x: 0.0808, y: 0.7548 },
  { number: 5, label: "T5", x: 0.3283, y: 0.6857 },
  { number: 6, label: "T6", x: 0.1478, y: 0.6519 },
  { number: 7, label: "T7", x: 0.4859, y: 0.3213 },
  { number: 8, label: "T8", x: 0.3403, y: 0.5312 },
  { number: 9, label: "T9", x: 0.5839, y: 0.3177 },
  { number: 10, label: "T10", x: 0.4791, y: 0.2749 },
  { number: 11, label: "T11", x: 0.645, y: 0.0836 },
  { number: 12, label: "T12", x: 0.8326, y: 0.147 },
  { number: 13, label: "T13", x: 0.6883, y: 0.1238 },
  { number: 14, label: "T14", x: 0.6034, y: 0.2136 },
  { number: 15, label: "T15", x: 0.7161, y: 0.2653 },
];

// Generated by scripts/build-whilton-maps.mjs alongside the artwork it labels. Re-run that
// script if the map changes; do not hand-edit.
export const BUILT_IN_WHILTON_INTERNATIONAL_CORNERS: TrackCorner[] = [
  { number: 1, label: "T1", x: 0.274, y: 0.4217 },
  { number: 2, label: "T2", x: 0.1383, y: 0.3182 },
  { number: 3, label: "T3", x: 0.8548, y: 0.148 },
  { number: 4, label: "T4", x: 0.7855, y: 0.2644 },
  { number: 5, label: "T5", x: 0.8533, y: 0.4279 },
  { number: 6, label: "T6", x: 0.5625, y: 0.5833 },
  { number: 7, label: "T7", x: 0.6608, y: 0.256 },
  { number: 8, label: "T8", x: 0.3283, y: 0.2752 },
  { number: 9, label: "T9", x: 0.4601, y: 0.7212 },
  { number: 10, label: "T10", x: 0.6087, y: 0.7392 },
  { number: 11, label: "T11", x: 0.5754, y: 0.8249 },
  { number: 12, label: "T12", x: 0.318, y: 0.8251 },
];

/**
 * Bumped when the artwork or the corner list changes, so a device that already stored the map
 * picks up the new one. This revision drops the map's own background and theme so it follows the
 * app's light/dark toggle; the one before it renumbered the corners from the start straight.
 */
/**
 * Generated by scripts/build-silverstone-map.mjs alongside the artwork it labels. Re-run that
 * script if the map changes; do not hand-edit.
 *
 * These run in the circuit's own order: the owner confirmed it runs anti-clockwise, which the
 * generator orients the lap to. Where they start is still a convention — nothing in the source
 * marks a start line, so the generator begins the lap at the northernmost point to keep the
 * numbering stable between runs. So T1 is not necessarily the circuit's Turn 1, but T5 does follow
 * T4 the way a driver meets them.
 */
export const BUILT_IN_SILVERSTONE_GRAND_PRIX_CORNERS: TrackCorner[] = [
  { number: 1, label: "T1", x: 0.4771, y: 0.3768 },
  { number: 2, label: "T2", x: 0.3726, y: 0.4066 },
  { number: 3, label: "T3", x: 0.3647, y: 0.4759 },
  { number: 4, label: "T4", x: 0.0936, y: 0.6703 },
  { number: 5, label: "T5", x: 0.1296, y: 0.7245 },
  { number: 6, label: "T6", x: 0.6499, y: 0.3011 },
  { number: 7, label: "T7", x: 0.8186, y: 0.5397 },
  { number: 8, label: "T8", x: 0.8459, y: 0.5421 },
  { number: 9, label: "T9", x: 0.2704, y: 0.8294 },
  { number: 10, label: "T10", x: 0.5059, y: 0.6392 },
  { number: 11, label: "T11", x: 0.3809, y: 0.77 },
  { number: 12, label: "T12", x: 0.6095, y: 0.5675 },
  { number: 13, label: "T13", x: 0.7408, y: 0.5248 },
  { number: 14, label: "T14", x: 0.9066, y: 0.3655 },
  { number: 15, label: "T15", x: 0.7907, y: 0.3582 },
];

/**
 * Generated by scripts/build-buckmore-map.mjs alongside the artwork it labels. Re-run that script
 * if the map changes; do not hand-edit.
 *
 * Both the lap and its clockwise direction come from OpenStreetMap, which maps this circuit as one
 * closed way tagged oneway=yes — so unlike Kart Silverstone nothing here was chosen. The lap starts
 * at the pit exit, the nearest thing the source records to a start line. Twelve corners, which is
 * also the number the circuit publishes.
 */
export const BUILT_IN_BUCKMORE_PARK_CORNERS: TrackCorner[] = [
  { number: 1, label: "T1", x: 0.8752, y: 0.4436 },
  { number: 2, label: "T2", x: 0.7874, y: 0.3719 },
  { number: 3, label: "T3", x: 0.483, y: 0.4298 },
  { number: 4, label: "T4", x: 0.1712, y: 0.7247 },
  { number: 5, label: "T5", x: 0.094, y: 0.6474 },
  { number: 6, label: "T6", x: 0.3023, y: 0.5201 },
  { number: 7, label: "T7", x: 0.1702, y: 0.6785 },
  { number: 8, label: "T8", x: 0.3808, y: 0.5486 },
  { number: 9, label: "T9", x: 0.3641, y: 0.4468 },
  { number: 10, label: "T10", x: 0.5266, y: 0.3147 },
  { number: 11, label: "T11", x: 0.7045, y: 0.3314 },
  { number: 12, label: "T12", x: 0.7899, y: 0.2453 },
];

const WHILTON_VERSION = "2026-08-20-theme-neutral";

export const BUILT_IN_TRACKS: BuiltInTrack[] = [
  {
    key: "pf-international",
    name: "PF International",
    location: "Grantham, UK",
    notes: "",
    direction: "Clockwise",
    attribution: OSM_ATTRIBUTION,
    sourceUrl: OSM_SOURCE_URL,
    layouts: [{
      key: "pfi-full",
      name: "Full Layout",
      mapUrl: "/maps/pfi-international-owner-driver.svg",
      version: "2026-08-20-theme-neutral",
      corners: BUILT_IN_PFI_CORNERS,
    }],
  },
  {
    key: "whilton-mill",
    name: "Whilton Mill",
    location: "Daventry, UK",
    // The lap length is the measured centreline of the OpenStreetMap geometry, which runs shorter
    // than the figures the circuit publishes. Recorded here so the number on the map is not
    // mistaken for an official distance.
    notes: "The lap length shown on the map is measured along the OpenStreetMap centreline, not the circuit's published distance.",
    direction: "Clockwise",
    attribution: OSM_ATTRIBUTION,
    sourceUrl: OSM_SOURCE_URL,
    layouts: [{
      key: "whilton-international",
      name: "International",
      mapUrl: "/maps/whilton-mill-international.svg",
      version: WHILTON_VERSION,
      corners: BUILT_IN_WHILTON_INTERNATIONAL_CORNERS,
    }],
  },
  {
    key: "kart-silverstone",
    name: "Kart Silverstone",
    location: "Silverstone, UK",
    // Shown on the track page. This circuit is the one built-in whose layout is not established by
    // its source, so the uncertainty is stated to the user rather than only in the code.
    notes: "Reconstructed from OpenStreetMap, which records no circuit definition here. The lap drawn is the closest match to the 1,377 m the circuit publishes for its Grand Prix layout, not a confirmed one. It runs anti-clockwise, and the corners are numbered in that order, but nothing in the source marks a start line — so T1 is where this app starts counting, not necessarily where the circuit does.",
    direction: "Anti-clockwise",
    attribution: OSM_ATTRIBUTION,
    sourceUrl: OSM_SOURCE_URL,
    layouts: [{
      key: "silverstone-grand-prix",
      name: "Grand Prix",
      mapUrl: "/maps/silverstone-grand-prix.svg",
      version: "2026-08-28-anti-clockwise",
      corners: BUILT_IN_SILVERSTONE_GRAND_PRIX_CORNERS,
    }],
  },
  {
    key: "buckmore-park",
    name: "Buckmore Park",
    location: "Chatham, UK",
    // The published length is 929 m; the map says 854 m because it measures the OpenStreetMap
    // centreline, as the other built-in maps do.
    notes: "The lap length on the map is the measured OpenStreetMap centreline, which runs shorter than the 929 m the circuit publishes.",
    direction: "Clockwise",
    attribution: OSM_ATTRIBUTION,
    sourceUrl: OSM_SOURCE_URL,
    layouts: [{
      key: "buckmore-park-circuit",
      name: "Full Circuit",
      mapUrl: "/maps/buckmore-park.svg",
      version: "2026-08-30-osm-derived",
      corners: BUILT_IN_BUCKMORE_PARK_CORNERS,
    }],
  },
];

const layoutsByKey = new Map(BUILT_IN_TRACKS.flatMap((track) => track.layouts.map((layout) => [layout.key, { track, layout }] as const)));

/**
 * Loads a map that ships with the app. Width and height come from the file's own viewBox rather
 * than being hard-coded at the call site: marker positions are stored as fractions of the asset
 * box, so a stored size that disagrees with the artwork letterboxes the image and drifts every
 * marker placed on it.
 */
export async function loadBuiltInMapAsset(url: string): Promise<MapAsset> {
  const response = await fetch(url);
  if (!response.ok) throw new Error("Built-in map unavailable.");
  const markup = await response.text();

  const viewBox = markup.match(/viewBox\s*=\s*"\s*[\d.-]+\s+[\d.-]+\s+([\d.]+)\s+([\d.]+)/);
  const width = Number(viewBox?.[1]);
  const height = Number(viewBox?.[2]);
  if (!Number.isFinite(width) || !Number.isFinite(height) || width <= 0 || height <= 0) {
    throw new Error("Built-in map has no usable viewBox.");
  }

  const blob = new Blob([markup], { type: "image/svg+xml" });
  return {
    id: crypto.randomUUID(),
    blob,
    width,
    height,
    mimeType: "image/svg+xml",
    size: blob.size,
    updatedAt: new Date().toISOString(),
  };
}

/** The fields a stored layout needs in order to carry, and later recognise, a built-in map. */
export function builtInLayoutFields(track: BuiltInTrack, layout: BuiltInLayout, asset: MapAsset) {
  return {
    mapAssetId: asset.id,
    sourceAttribution: track.attribution,
    sourceUrl: track.sourceUrl,
    builtInLayoutKey: layout.key,
    builtInMapVersion: layout.version,
    corners: layout.corners,
  };
}

/**
 * Identifies the built-in layout a stored record came from.
 *
 * The key is authoritative. Records created before keys existed have none, so PF International is
 * also matched on the track and layout names it was created with — the only built-in track that
 * could have been stored back then. That fallback is deliberately not extended to Whilton Mill:
 * no unkeyed Whilton Mill record can exist, so name-matching one could only ever capture a track
 * the user built themselves and overwrite their map.
 */
function builtInLayoutFor(data: TrackMapData, layout: TrackLayout) {
  if (layout.builtInLayoutKey) return layoutsByKey.get(layout.builtInLayoutKey);

  const track = data.tracks.find((candidate) => candidate.id === layout.trackId);
  const isLegacyPfi = track?.name.trim().toLowerCase() === "pf international" && layout.name.trim().toLowerCase() === "full layout";
  return isLegacyPfi ? layoutsByKey.get("pfi-full") : undefined;
}

/**
 * Attaches built-in maps to layouts that need one, and replaces the artwork on layouts still
 * holding an older version of it.
 *
 * A layout whose map the user replaced has no `sourceAttribution` (uploadImage clears it), which
 * is what marks it as user-owned and off-limits here. Returns the input unchanged when there is
 * nothing to do, so callers can assign the result unconditionally.
 */
export async function refreshBuiltInMaps(data: TrackMapData): Promise<TrackMapData> {
  const stale = data.layouts
    .map((layout) => ({ layout, builtIn: builtInLayoutFor(data, layout) }))
    .filter((entry): entry is { layout: TrackLayout; builtIn: NonNullable<ReturnType<typeof builtInLayoutFor>> } => {
      if (!entry.builtIn) return false;
      const carriesBuiltInMap = !entry.layout.mapAssetId || Boolean(entry.layout.sourceAttribution);
      return carriesBuiltInMap && entry.layout.builtInMapVersion !== entry.builtIn.layout.version;
    });
  if (!stale.length) return data;

  // One fetch per distinct map, however many layouts are waiting on it.
  const urls = [...new Set(stale.map((entry) => entry.builtIn.layout.mapUrl))];
  const assets = new Map(await Promise.all(urls.map(async (url) => [url, await loadBuiltInMapAsset(url)] as const)));

  const fieldsByLayoutId = new Map(stale.map((entry) => [
    entry.layout.id,
    {
      ...builtInLayoutFields(entry.builtIn.track, entry.builtIn.layout, assets.get(entry.builtIn.layout.mapUrl)!),
      // Fills a direction that was never chosen — records created before the registry knew one
      // were all stamped Unknown. A direction the user picked is left alone.
      ...(entry.layout.direction === "Unknown" ? { direction: entry.builtIn.track.direction } : {}),
    },
  ]));
  const replacedAssetIds = new Set(stale.map((entry) => entry.layout.mapAssetId).filter((id): id is string => Boolean(id)));
  const timestamp = new Date().toISOString();

  return {
    ...data,
    assets: [...data.assets.filter((candidate) => !replacedAssetIds.has(candidate.id)), ...assets.values()],
    layouts: data.layouts.map((layout) => {
      const fields = fieldsByLayoutId.get(layout.id);
      return fields ? { ...layout, ...fields, updatedAt: timestamp } : layout;
    }),
  };
}

/**
 * Builds the Track and Layout records for a built-in circuit, ready to append to the store.
 *
 * A map that fails to load is not fatal: the track is still created without one, and
 * refreshBuiltInMaps attaches the artwork on a later load once the file is reachable.
 */
export async function createBuiltInTrack(track: BuiltInTrack, timestamp: string) {
  const trackId = crypto.randomUUID();
  const assets: MapAsset[] = [];

  const layouts = await Promise.all(track.layouts.map(async (layout) => {
    let asset: MapAsset | undefined;
    try {
      asset = await loadBuiltInMapAsset(layout.mapUrl);
      assets.push(asset);
    } catch {
      // Leave the layout without a map; the user can upload one or reload to pick it up.
    }
    return {
      id: crypto.randomUUID(),
      trackId,
      name: layout.name,
      direction: track.direction,
      // The key and corners are stored either way, so a layout whose artwork failed to load is
      // still recognised as built-in and picks the map up on a later load.
      ...(asset
        ? builtInLayoutFields(track, layout, asset)
        : { mapAssetId: null, builtInLayoutKey: layout.key, corners: layout.corners }),
      markers: [],
      createdAt: timestamp,
      updatedAt: timestamp,
    } satisfies TrackLayout;
  }));

  return {
    track: { id: trackId, name: track.name, location: track.location, notes: track.notes, createdAt: timestamp, updatedAt: timestamp },
    layouts,
    assets,
    mapsLoaded: assets.length,
  };
}
